kind: pipeline
type: docker
name: docker-volume-backup

steps:
- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: adamkoro/docker-volume-backup
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}