version: "3.7"
services:
  backup:
    image: "adamkoro/docker-volume-backup:latest"
    container_name: "backup"
    restart: "never"
    volumes:
      - "docker-tmp-backup:/backup:ro"
    environment:
      - S3_BUCKET=backup
      - S3_ENDPOINT=https://s3.eu-central-1.amazonaws.com
      - S3_ACCESS_KEY=xxx
      - S3_SECRET_KEY=xxx
      - S3_REGION=eu-central-1
      - S3_SSL=true
      - BACKUP_NAME=backup

volumes:
  docker-tmp-backup:
